### ISSUE TITLE
Spacemacs Rocks 第二季文本网页阅读版

### ISSUE THREAD

**Issue by li-xinyang** [emacser-cn/Spacemacs-rocks#40]
我暂时将网页阅读版的域名放在我之前购买的一个域名下，下面是一个简单的 Demo。

http://emacs.frontseat.io/

@zilongshanren 你觉得域名买 `spacemacsrocks.com` 好还少 `spacemacs-rocks.com` 好呢？但是这样的域名会不会限制之后的我们内容的扩展呢？比如我们如果有 Org-mode 的讨论？或者如果你愿意放在你的域名下也行 `emacs.zilongshanren.com`。决定好我就去买域名啦 :dancer: 

我想这样可以让我们更容易的和同时学习 Emacs 的朋友有更直接的交流，也不用一直读 README，还可以内嵌视频。也可以之后在这个域名下做 Emacs 的中文 Discourse 社区。

域名和最后方案决定后我会去做主题的移动适配。

**Comment by zilongshanren** [comment]
我有一个 emacser.cn， 你觉得怎么样？

**Comment by zilongshanren** [comment]
@li-xinyang  现在 emacser.cn 也有一个 single page 页面，只是没内容。

**Comment by zilongshanren** [comment]
@li-xinyang  https://github.com/emacser-cn/emacser-cn 我可以把你设置为这个 organization 的 admin

我之前的仓库都已经建立好了。。 https://github.com/emacser-cn/Learn-Emacs-in-21-days

**Comment by li-xinyang** [comment]
好哒，那我之后把内容想办法转移过去。现在这个主题太丑了 :sob:

**Comment by zilongshanren** [comment]
@li-xinyang  你现在是 owner 了 😄   不过两个仓库分离会不会不太好？ 我直接把这个仓库弄过去？

**Comment by zilongshanren** [comment]
@li-xinyang  这个仓库挂到 emacser-cn 这个组织下面去？

**Comment by zilongshanren** [comment]
@li-xinyang  你有 skype 么？ 我觉得我们两个需要好好聊一下这个事...  我们要打造一个最好的 Emacs 中文社区 😄

**Comment by zilongshanren** [comment]
@li-xinyang  我在 emacs-cn slack 上面私信你了

**Comment by li-xinyang** [comment]
我有 skype，我回家才能上。单位网屏蔽了。我都听师傅的，我只能帮忙。我自己感觉才刚刚入门，就尽我所能帮大家做一些事儿咯。让我下一个 Slack 我那天删了，因为你们聊的我都插不上。

**Comment by zilongshanren** [comment]
@li-xinyang OK， 我们在 slack 上面再详聊
