### ISSUE TITLE
define-abbrev-table 缩写展开无法生效

### ISSUE THREAD

**Issue by ziyuanjun** [emacser-cn/Spacemacs-rocks#42]
#Emacs 版本#： GNU Emacs 25.1.50.1
#操作系统#： LXLE 14.04 LTS

#语句#：
(abbrev-mode t)
(define-abbrev-table 'global-abbrev-table '(
					    ;;me
					    ("8zy" "ziyuan")
					    ;;mic
					    ("8ms" "Microsoft")
					    ))
#现象#：敲完8zy后按空格或tab都不会变成我想要的字符串。

**Comment by li-xinyang** [comment]
```
;; Abbreviation Mode and Setting
(abbrev-mode 1)
(define-abbrev-table 'global-abbrev-table '(
					    ("3lxy" "li-xinyang")
```

我这里没问题，能不能给你全部编辑器的配置信息。

**Comment by ziyuanjun** [comment]
我编辑器的全部配置都是照着山人的视频一句一句敲的，我也觉得很奇怪

**Comment by ziyuanjun** [comment]
在define-abbrev-table的最后 C-x C-e，输出字符nil，
你的也是这样的吗？

**Comment by zilongshanren** [comment]
@ziyuanjun   我也是输出 nil... 不过这并不影响。

**Comment by zilongshanren** [comment]
@ziyuanjun  你试一下手动在当前 buffer 调用 M-x abbrev-mode 试试

**Comment by zilongshanren** [comment]
@ziyuanjun  `C-h m` 把你的输出拿出来看看。。

**Comment by ziyuanjun** [comment]
@zilongshanren 在当前buffer 调用 M-x abbrev-mode就可以啦！
C-h m 的输出（调用 M-x abbrev-mode之前）：
Enabled minor modes: Auto-Composition Auto-Compression Auto-Encryption
Blink-Cursor Company Delete-Selection Diff-Auto-Refine Electric-Indent
File-Name-Shadow Font-Lock Global-Auto-Revert Global-Company
Global-Eldoc Global-Font-Lock Global-Hl-Line Global-Hungry-Delete
Global-Linum Hungry-Delete Ivy Line-Number Linum Menu-Bar Mouse-Wheel
Popwin Recentf Show-Paren Smartparens Smartparens-Global Tooltip
Transient-Mark

调用后：
Enabled minor modes: Abbrev Auto-Composition Auto-Compression
Auto-Encryption Blink-Cursor Company Delete-Selection Diff-Auto-Refine
Electric-Indent File-Name-Shadow Font-Lock Global-Auto-Revert
Global-Company Global-Eldoc Global-Font-Lock Global-Hl-Line
Global-Hungry-Delete Global-Linum Hungry-Delete Ivy Line-Number Linum
Menu-Bar Mouse-Wheel Popwin Recentf Show-Paren Smartparens
Smartparens-Global Tooltip Transient-Mark

**Comment by li-xinyang** [comment]
@ziyuanjun 我觉得你也学要检查下配置文件诶 一句句敲可能会敲错的 @zilongshanren 师傅，我回 S 国了，可以更新文字版啦。

**Comment by zilongshanren** [comment]
@li-xinyang  上周的视频我这周末补上，上周比较忙，没有来得及录。

**Comment by zilongshanren** [comment]
@ziyuanjun

在你的配置里面添加 :  `(setq only-global-abbrevs t)` 就好了。
